version: '3.8'
services:
  eureka-server:
    build:
      context: ./eureka-server
      dockerfile: Dockerfile
    image: eureka-server:latest
    ports:
      - "8761:8761"
    networks:
      - app-network
  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    image: api-gateway:latest
    depends_on:
      - eureka-server
    ports:
      - "8888:8888"
    environment:
      - EUREKA_URL=http://42.112.26.140:8761
    networks:
      - app-network
  user-service:
    build:
      context: ./user-service
      dockerfile: Dockerfile
    image: user-service:latest
    depends_on:
      - eureka-server
    ports:
      - "8081:8081"
    networks:
      - app-network
  category-service:
    build:
      context: ./category-service
      dockerfile: Dockerfile
    image: category-service:latest
    depends_on:
      - eureka-server
    ports:
      - "8082:8082"
    networks:
      - app-network
  product-service:
    build:
      context: ./product-service
      dockerfile: Dockerfile
    image: product-service:latest
    depends_on:
      - eureka-server
    ports:
      - "8083:8083"
    networks:
      - app-network
  file-service:
    build:
      context: ./file-service
      dockerfile: Dockerfile
    image: file-service:latest
    depends_on:
      - eureka-server
    ports:
      - "8084:8084"
    networks:
      - app-network
  shop-service:
    build:
      context: ./shop-service
      dockerfile: Dockerfile
    image: shop-service:latest
    depends_on:
      - eureka-server
    ports:
      - "8085:8085"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge