version: '3.8'
services:
  product-service:
    build:
      context: ./product-service
      dockerfile: Dockerfile
    image: product-service:latest
    depends_on:
      - common-service
    ports:
      - "8083:8083"
